name: Lizard-runner
on:
    pull_request:
        branches:
            - main

permissions:
    contents: read
    pull-requests: write

jobs:
    lizard:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v6
              with:
                python-version: '3.13'
            - uses: actions/checkout@v5
              with:
                fetch-depth: 0
            - name: Run Lizard script on changed files
              run: |
                  pip install lizard

                  BASE_SHA="${{ github.event.pull_request.base.sha }}"
                  HEAD_SHA="${{ github.event.pull_request.head.sha }}"

                  git fetch --no-tags origin "$BASE_SHA" "$HEAD_SHA"

                  CHANGED_FILES=$(git diff --name-only --diff-filter=ACMR "$BASE_SHA" "$HEAD_SHA")

                  TOTAL_COMPLEXITY=$(python -c "
                  import lizard, sys
                  total = 0
                  for file_path in sys.argv[1:]:
                      result = lizard.analyze_file(file_path)
                      for func in result.function_list:
                          total += func.cyclomatic_complexity
                  print(total)
                  " $CHANGED_FILES)

                  echo "Total Cyclomatic Complexity of changed files: $TOTAL_COMPLEXITY"
                  echo "TOTAL_COMPLEXITY=$TOTAL_COMPLEXITY" >> $GITHUB_ENV
            - name: Add comment to PR with complexity result
              env:
                GH_TOKEN: ${{ github.token }}
              run: |
                COMMENT_ID=$(gh api "repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" -q '.[] | select(.user.login=="github-actions[bot]" and (.body | contains("Lizard Cyclomatic Complexity"))) | .id' | head -n 1)

                if [ -n "$COMMENT_ID" ]; then
                  gh api -X DELETE "repos/${{ github.repository }}/issues/comments/${COMMENT_ID}"
                fi

                gh pr comment "${{ github.event.pull_request.number }}" --body "## Lizard Cyclomatic Complexity Score: ${{ env.TOTAL_COMPLEXITY }}"

