name: Lizard-runner
on:
    pull_request:
        branches:
            - main

permissions:
    contents: read
    pull-requests: write

jobs:
    lizard:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v6
              with:
                python-version: '3.13'
            - uses: actions/checkout@v5
              with:
                fetch-depth: 0
            - name: Run Lizard script on changed files
              run: |
                  pip install lizard

                  BASE_SHA="${{ github.event.pull_request.base.sha }}"
                  HEAD_SHA="${{ github.event.pull_request.head.sha }}"

                  git fetch --no-tags origin "$BASE_SHA" "$HEAD_SHA"

                  CHANGED_FILES=$(git diff --name-only --diff-filter=ACMR "$BASE_SHA" "$HEAD_SHA")

                  python -c "
                  import lizard, sys
                  individual_scores = {}
                  average = 0
                  for file_path in sys.argv[1:]:
                      result = lizard.analyze_file(file_path)
                      file_score = 0
                      for func in result.function_list:
                          file_score += func.cyclomatic_complexity
                      if len(result.function_list) > 0:
                          individual_scores[file_path] = file_score / len(result.function_list)
                      else:
                          individual_scores[file_path] = 0
                  if len(individual_scores.values()) > 0:
                      average = sum(individual_scores.values()) / len(individual_scores.values())
                  lines = ['## Lizard Cyclomatic Complexity', '', f'PR Complexity : {average:.2f}', '', 'Files:']
                  for filepath, score in individual_scores.items():
                      lines.append(f'- {filepath} : {score:.2f}')
                  with open('complexity_comment.md', 'w') as f:
                      f.write('\n'.join(lines))
                  " $CHANGED_FILES
            - name: Add comment to PR with complexity result
              env:
                GH_TOKEN: ${{ github.token }}
              run: |
                COMMENT_ID=$(gh api "repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" -q '.[] | select(.user.login=="github-actions[bot]" and (.body | contains("Lizard Cyclomatic Complexity"))) | .id' | head -n 1)

                if [ -n "$COMMENT_ID" ]; then
                  gh api -X DELETE "repos/${{ github.repository }}/issues/comments/${COMMENT_ID}"
                fi

                gh pr comment "${{ github.event.pull_request.number }}" --body-file complexity_comment.md

