name: Lizard-runner
on:
    pull_request:
        branches:
            - main

permissions:
    contents: read
    pull-requests: write

jobs:
    lizard:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v6
              with:
                python-version: '3.13'
            - uses: actions/checkout@v5
              with:
                fetch-depth: 0
            - name: Run Lizard script on changed files
              run: |
                  pip install lizard

                  BASE_SHA="${{ github.event.pull_request.base.sha }}"
                  HEAD_SHA="${{ github.event.pull_request.head.sha }}"

                  git fetch --no-tags origin "$BASE_SHA" "$HEAD_SHA"

                  CHANGED_FILES=$(git diff --name-only --diff-filter=ACMR "$BASE_SHA" "$HEAD_SHA")

                  AVERAGE_COMPLEXITY=$(lizard --csv $CHANGED_FILES \
                  | awk -F',' 'NR>1 {sum+=$2; count++} END {if(count>0) printf "%.2f", sum/count; else print "0"}')

                  printf '## Lizard Cyclomatic Complexity\n\nPR Complexity: %s\n' "$AVERAGE_COMPLEXITY" > complexity_comment.md

            - name: Add comment to PR with complexity result
              env:
                GH_TOKEN: ${{ github.token }}
                GITHUB_REPOSITORY: ${{ github.repository }}
                GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
              run: |
                COMMENT_ID=$(gh api "repos/${GITHUB_REPOSITORY}/issues/${GITHUB_PULL_REQUEST_NUMBER}/comments" -q '.[] | select(.user.login=="github-actions[bot]" and (.body | contains("Lizard Cyclomatic Complexity"))) | .id' | head -n 1)

                [ -n "$COMMENT_ID" ] && gh api -X DELETE "repos/${GITHUB_REPOSITORY}/issues/comments/${COMMENT_ID}"

                gh pr comment "$GITHUB_PULL_REQUEST_NUMBER" --body-file complexity_comment.md

