name: Convert Markdown (slides) to PPTX

on:
  push:
    branches: [develop, main]
    paths:
      - "**/*slides*.md"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate PowerPoint from Markdown
        uses: KoharaKazuya/marp-cli-action@v2
        with:
          generate-pptx: true

      - name: Commit generated PPTX
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update generated PPTX slides"
          file_pattern: "*.pptx"
